-- Тест-набор фильтра public.moderate_text (см. DECISIONS.md, «Модерация текста»).
-- Прогонять через Supabase MCP execute_sql после любой правки словаря:
-- ожидается failed = 0. Первая половина — нормальные фразы, в которых
-- встречаются корни мата (корабля, застрахуй, команда, себе…), вторая —
-- то, что обязано блокироваться, включая обходы (х.у.й, XУЙ, 6ля, pizdec).
with cases(txt, ctx, expect) as (values
  -- должно пропускать
  ('Вот это судак!', 'comment', null),
  ('На что клюнул?', 'comment', null),
  ('Корабля не видно с берега', 'comment', null),
  ('Употреблять только свежую наживку', 'comment', null),
  ('Оскорблять никого не хочу', 'comment', null),
  ('Команда у нас огонь', 'comment', null),
  ('Командир рыбалки сегодня Руслан', 'comment', null),
  ('Мандарины и чай на рыбалке', 'comment', null),
  ('Мандат на ловлю', 'comment', null),
  ('Скипидар для лодки', 'comment', null),
  ('Застрахуй лодку', 'comment', null),
  ('Страхую тебя с берега', 'comment', null),
  ('Он страхует новичков', 'comment', null),
  ('Небо ясное, клёв отличный', 'comment', null),
  ('Хлеб как прикормка работает', 'comment', null),
  ('Хлебать уху у костра', 'comment', null),
  ('Себе оставил, отпустил мелкую', 'comment', null),
  ('Как тебе такой улов?', 'comment', null),
  ('Вебинар по спиннингу', 'comment', null),
  ('Бляха от ремня упала в воду', 'comment', null),
  ('Хулиган клюнул', 'comment', null),
  ('Сук упал в воду', 'comment', null),
  ('Сукно на лодке промокло', 'comment', null),
  ('Педро поймал карпа', 'comment', null),
  ('Мудрый совет, спасибо', 'comment', null),
  ('Херсон далеко', 'comment', null),
  ('Херувим на иконе', 'comment', null),
  ('Даунтаун Батуми', 'comment', null),
  ('Потребляет много бензина', 'comment', null),
  ('Учебник рыбака', 'comment', null),
  ('Требовать нечего', 'comment', null),
  ('Колеблюсь, куда ехать', 'comment', null),
  ('Уха из судака', 'comment', null),
  ('Ухаживай за снастями', 'comment', null),
  ('Похудел на рыбалке', 'comment', null),
  ('Застрахуюсь на всякий', 'comment', null),
  ('Хуже не бывает', 'comment', null),
  ('Хуан тоже рыбак', 'comment', null),
  ('Рубля не стоит', 'comment', null),
  ('Гребля на рассвете', 'comment', null),
  ('Сабля на стене', 'comment', null),
  ('Оскорбление недопустимо', 'comment', null),
  ('Human error', 'comment', null),
  ('Hue shift on photo', 'comment', null),
  ('eBay лучше не надо', 'comment', null),
  ('Первая поклёвка в 6:40', 'comment', null),
  ('Размер 62 см, вес 2400 г', 'comment', null),
  ('Сектор B1608 мой', 'comment', null),
  ('ОГО', 'comment', null),
  ('Супер улов, Руслан!', 'comment', null),
  ('Ааа класс', 'comment', null),
  ('Поймал 3 окуня и 2 карася', 'comment', null),
  ('И у меня так было', 'comment', null),
  ('Чмок тебе за улов', 'comment', null),
  ('Уродился хороший год', 'comment', null),
  ('Тварь божья эта рыба', 'comment', 'profanity'),
  ('Щуки Батуми', 'clan_name', null),
  ('Морские волки', 'clan_name', null),
  ('Клан-команда', 'clan_name', null),
  -- должно блокировать: мат
  ('хуй', 'comment', 'profanity'),
  ('Хуйня какая-то', 'comment', 'profanity'),
  ('иди нахуй', 'comment', 'profanity'),
  ('мне похуй', 'comment', 'profanity'),
  ('охуенно', 'comment', 'profanity'),
  ('х у й', 'comment', 'profanity'),
  ('х.у.й', 'comment', 'profanity'),
  ('XУЙ', 'comment', 'profanity'),
  ('хууууй', 'comment', 'profanity'),
  ('xyйня', 'comment', 'profanity'),
  ('х*й', 'comment', 'profanity'),
  ('пизда', 'comment', 'profanity'),
  ('пиздец', 'comment', 'profanity'),
  ('п*здец', 'comment', 'profanity'),
  ('Пиздато', 'comment', 'profanity'),
  ('блядь', 'comment', 'profanity'),
  ('Бля', 'comment', 'profanity'),
  ('блять', 'comment', 'profanity'),
  ('6ля', 'comment', 'profanity'),
  ('сука', 'comment', 'profanity'),
  ('сyка', 'comment', 'profanity'),
  ('Суки', 'comment', 'profanity'),
  ('ебать', 'comment', 'profanity'),
  ('ебаный', 'comment', 'profanity'),
  ('ёбаный', 'comment', 'profanity'),
  ('заебал', 'comment', 'profanity'),
  ('выебал', 'comment', 'profanity'),
  ('уебок', 'comment', 'profanity'),
  ('долбоеб', 'comment', 'profanity'),
  ('долбоёб', 'comment', 'profanity'),
  ('еблан', 'comment', 'profanity'),
  ('съебался', 'comment', 'profanity'),
  ('мудак', 'comment', 'profanity'),
  ('мудило', 'comment', 'profanity'),
  ('пидор', 'comment', 'profanity'),
  ('пидр', 'comment', 'profanity'),
  ('гандон', 'comment', 'profanity'),
  ('шлюха', 'comment', 'profanity'),
  ('залупа', 'comment', 'profanity'),
  ('манда', 'comment', 'profanity'),
  ('дрочить', 'comment', 'profanity'),
  ('херня', 'comment', 'profanity'),
  ('да пошёл ты нахер', 'comment', 'profanity'),
  ('мразь', 'comment', 'profanity'),
  ('ублюдок', 'comment', 'profanity'),
  ('чмо', 'comment', 'profanity'),
  ('ты дебил', 'comment', 'profanity'),
  ('урод', 'comment', 'profanity'),
  ('гнида', 'comment', 'profanity'),
  ('падла', 'comment', 'profanity'),
  ('сволочь', 'comment', 'profanity'),
  ('pizdec', 'comment', 'profanity'),
  ('blyat', 'comment', 'profanity'),
  ('suka', 'comment', 'profanity'),
  ('nahui', 'comment', 'profanity'),
  ('huy', 'comment', 'profanity'),
  ('ebal', 'comment', 'profanity'),
  ('fuck you', 'comment', 'profanity'),
  ('Щуки-пидоры', 'clan_name', 'profanity'),
  ('улов-хуйня', 'comment', 'profanity'),
  -- ссылки, телефоны
  ('заходи на site.ru', 'comment', 'link'),
  ('https://t.me/abc', 'comment', 'link'),
  ('пиши @ivanfisher', 'comment', 'link'),
  ('www.fish.com', 'comment', 'link'),
  ('рыбалка.рф', 'comment', 'link'),
  ('+995 555 12 34 56', 'comment', 'phone'),
  ('звони 89161234567', 'comment', 'phone'),
  -- капс, повторы, длина, пусто
  ('ВОТ ЭТО УЛОВ БРАТ', 'comment', 'caps'),
  ('ааааааааа', 'comment', 'repeat'),
  ('🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟', 'comment', 'repeat'),
  ('   ', 'comment', 'empty'),
  (repeat('рыба ', 70), 'comment', 'too_long'),
  ('Клан RANGE', 'clan_name', 'reserved'),
  ('Админы', 'clan_name', 'reserved'),
  ('Официальный клан', 'clan_name', 'reserved'),
  -- чат клана: мат разрешён, остальные правила — как везде
  ('иди нахуй', 'clan_chat', null),
  ('пиздец клёв сегодня', 'clan_chat', null),
  ('blyat, опять сорвалась', 'clan_chat', null),
  ('хуй там, заходи на site.ru', 'clan_chat', 'link'),
  ('звони 89161234567', 'clan_chat', 'phone'),
  ('ВОТ ЭТО УЛОВ БРАТ', 'clan_chat', 'caps'),
  ('ааааааааа', 'clan_chat', 'repeat')
)
select count(*) filter (where public.moderate_text(txt, ctx) is distinct from expect) as failed,
       count(*) as total,
       string_agg(case when public.moderate_text(txt, ctx) is distinct from expect
                  then txt || ' → ' || coalesce(public.moderate_text(txt, ctx), 'ok') end, ' | ') as failures
from cases;
